name: Tests by Cypress

on:

  # schedule:
  #   - cron: '30 22 * * *'
  #push:
  #  branches: 
  #  - 'master' # [ main ]
  #  # Publish semver tags as releases.
  #  #tags: none # [ 'v*.*.*' ]
  #  
  #pull_request:
  #  branches: 
  #  - 'master' # [ main ]

  
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: servicewebapp112aa  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './published'      # set this to the path to your web app project, defaults to the repository root
  NETCORE_VERSION: '7.0.x'                    # set this to the .NET Core version to use
  
jobs:
  
  cypress-run:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v3
      
    - name: Set up Node.js version
      uses: actions/setup-node@v3
    
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    
    - name: Restore packages
      run: dotnet restore

    - name: Build app
      run: dotnet build --configuration Release --no-restore

    - name: Test app
      run: dotnet test --no-build
      
    - name: load cypress
      uses: cypress-io/github-action@v5
      with:
        build: npm run build
        start: npm start
        browser: chrome
        record: true
      env:
        # pass the Cypress Cloud record key as an environment variable
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        # pass GitHub token to allow accurately detecting a build vs a re-run build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
