name: Tests by Cypress Manual

on:
  workflow_dispatch:
  
  
jobs:
  
  cypress-run:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v3
      
      
    - name: load cypress
      uses: cypress-io/github-action@v5
      with:
        runTests: false
        
