name: Tests by Cypress Manual

on:
  workflow_dispatch:
  
  
env:  
  NETCORE_VERSION: '7.0.x'

jobs:
  
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@master

      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Restore packages
        run: dotnet restore

      - name: echo
        run: printenv $CYPRESS_RECORD_KEY 

      - name: run tests
        uses: cypress-io/github-action@v5
        with:        
          build: dotnet build --configuration Release --no-restore
          start: dotnet run --no-restore
          runTests: true
          browser: chrome
          headed: false
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
