name: Tests by Cypress Manual

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 22 * * *'
  #push:
  #  branches: 
  #  - 'master' # [ main ]
  #  # Publish semver tags as releases.
  #  #tags: none # [ 'v*.*.*' ]
  #  
  #pull_request:
  #  branches: 
  #  - 'master' # [ main ]

  
env:  
  NETCORE_VERSION: '7.0.x'
  CYPRESS_RECORD_KEY: '079dcb48-f7d3-42fa-bb9c-7c63c476684e'

jobs:
  
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@master

      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Restore packages
        run: dotnet restore

      - name: run tests
        uses: cypress-io/github-action@v5
        with:        
          build: dotnet build --configuration Release --no-restore
          start: dotnet run --no-restore
          runTests: true
          browser: chrome
          headed: false
          record: true
        #env:
        #  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}          
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
