name: Tests by Cypress Manual

on:
  workflow_dispatch:
  
  
env:  
  NETCORE_VERSION: '7.0.x'

jobs:
  
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@master

      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Restore packages
        run: dotnet restore

      #- name: build packages
      #  run: dotnet build --configuration Release --no-restore

      #- name: run webapp localy
      #  run: dotnet run

      - name: run tests
        uses: cypress-io/github-action@v5
        with:        
          build: dotnet build --configuration Release --no-restore
          start: dotnet run --no-restore
          runTests: true
          browser: chrome
          headed: false
          record: true
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
