name: Tests by Cypress Docker

on:

  # schedule:
  #   - cron: '30 22 * * *'
  #push:
  #  branches: 
  #  - 'master' # [ main ]
  #  # Publish semver tags as releases.
  #  #tags: none # [ 'v*.*.*' ]
  #  
  #pull_request:
  #  branches: 
  #  - 'master' # [ main ]

  
  workflow_dispatch:
  
env:  
  NETCORE_VERSION: '7.0.x'                    # set this to the .NET Core version to use
  
jobs:
  
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.13.0-chrome78-ff70
    steps:

    - name: code checkout
      uses: actions/checkout@v3
      
    - name: load cypress
      uses: cypress-io/github-action@v5
      with:      
        browser: chrome
        record: true
      env:
        # pass the Cypress Cloud record key as an environment variable
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        # pass GitHub token to allow accurately detecting a build vs a re-run build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
