name: Docker manual

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - "master"

jobs:
  build-container:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        working-directory: .
        run: docker build . --file Dockerfile --tag my-app-dotnet:$(date +%s)
